config/routes.rb
Rails.application.routes.draw do
  devise_for :contributors
  resources :moment_types

  resources :tags

  resources :moments

  resources :race_days

  resources :races

  get "pages/dashboard", :to => "pages#dashboard", :as => "dashboard"

  root 'pages#main'

end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/moment.rb
class Moment < ActiveRecord::Base
  has_and_belongs_to_many :tags
  
  belongs_to :race_day
  
  scope :active_moments, -> {where(:active => true)}  
  
  def associate_tags_by_id_array(tag_id_array)
    self.tags = []
    tag_id_array.select{|a| a != ""}.each do |tag_id|
      self.tags << Tag.find_by(:id => tag_id) unless self.tags.include?(Tag.find_by(:id => tag_id))
    end
  end
  
  def geo_json_long_lat_array
      return [ self.long, self.lat ]
  end
end

app/models/race.rb
class Race < ActiveRecord::Base
  has_many :race_days
  
  belongs_to :start_day, class_name: 'RaceDay'
  belongs_to :end_day, class_name: 'RaceDay'

end

app/models/race_day.rb
class RaceDay < ActiveRecord::Base
  belongs_to :race
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :moments

  before_save do
    self.name = Tag.normalize_tag_name(self.name)
  end 
  
  scope :active_tags_with_moments_ordered, -> {where(:active => true).where(:id => Tag.select(:id).joins(:moments).group('tags.id') ).order(name: :asc)}
  
  
  def self.normalize_tag_name(string)
    if !string.nil? 
      return string.to_s.strip.gsub(/[^A-Za-z0-9\_\s]+/, "").gsub(/[_\s]+/, '_').downcase
    end
  end
  
  def self.build_tag_id_array_from_comma_seperated_string(string) 
    tags = []
     string.split(',').each do |tag_name|
       tag = Tag.find_or_initialize_by(:name => Tag.normalize_tag_name(tag_name.strip))
       tag.save
       tags << tag.id
     end
     
     return tags
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController
  before_action :set_moment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @moments = Moment.all
    respond_with(@moments)
  end

  def show
    respond_with(@moment)
  end

  def new
    @moment = Moment.new
    respond_with(@moment)
  end

  def edit
  end

  def create
    @moment = Moment.new(moment_params)
    @moment.save
    associate_tags_by_id_array(@moment)
    redirect_to moments_path
  end

  def update
    if @moment.update(moment_params)    
      associate_tags_by_id_array(@moment)
    
      redirect_to moments_path, :alert => "Moment succesfully updated"
    else  
      render action: 'edit'  
    end
    
  end

  def destroy
    @moment.destroy
    respond_with(@moment)
  end

  private
  
    def associate_tags_by_id_array(moment)
      tags = []
      if params.has_key?(:comma_seperated_tag_string)
        tags = Tag.build_tag_id_array_from_comma_seperated_string(params[:comma_seperated_tag_string])
      end
      if params[:moment].has_key?(:tag_ids)
        tags = params[:moment][:tag_ids] + tags
      end
      moment.associate_tags_by_id_array(tags)
    end
  
    def set_moment
      @moment = Moment.find(params[:id])
    end

    def moment_params
      params.require(:moment).permit(:name, :description, :source, :lat, :long, :tag_ids,:race_day_id, :active, :embedable_code)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_contributor!, :except => [:main]
  
  def main  

    @tags = Tag.active_tags_with_moments_ordered
    
    #create moment map feature by tag
    gon.jbuilder "app/views/moments/moments_collection_geo_json.json.jbuilder", as: "moments"
  end
  
  def dashboard
  end
end

app/controllers/race_days_controller.rb
class RaceDaysController < ApplicationController
  before_action :set_race_day, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @race_days = RaceDay.all
    respond_with(@race_days)
  end

  def show
    respond_with(@race_day)
  end

  def new
    @race_day = RaceDay.new
    respond_with(@race_day)
  end

  def edit
  end

  def create
    @race_day = RaceDay.new(race_day_params)
    @race_day.save
    respond_with(@race_day)
  end

  def update
    @race_day.update(race_day_params)
    respond_with(@race_day)
  end

  def destroy
    @race_day.destroy
    respond_with(@race_day)
  end

  private
    def set_race_day
      @race_day = RaceDay.find(params[:id])
    end

    def race_day_params
      params.require(:race_day).permit(:name, :race_date, :race_id)
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @races = Race.all
    respond_with(@races)
  end

  def show
    respond_with(@race)
  end

  def new
    @race = Race.new
    respond_with(@race)
  end

  def edit
  end

  def create
    @race = Race.new(race_params)
    @race.save
    respond_with(@race)
  end

  def update
    @race.update(race_params)
    respond_with(@race)
  end

  def destroy
    @race.destroy
    respond_with(@race)
  end

  private
    def set_race
      @race = Race.find(params[:id])
    end

    def race_params
      params.require(:race).permit(:name, :start_day_id, :end_day_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tags = Tag.all
    respond_with(@tags)
  end

  def show
    respond_with(@tag)
  end

  def new
    @tag = Tag.new
    respond_with(@tag)
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    respond_with(@tag)
  end

  def update
    @tag.update(tag_params)
    respond_with(@tag)
  end

  def destroy
    @tag.destroy
    respond_with(@tag)
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moment_types_helper.rb
module MomentTypesHelper
end

app/helpers/moments_helper.rb
module MomentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/race_days_helper.rb
module RaceDaysHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>OpenRallyMap</title>
	<%= include_gon %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <!-- Leaflet -->    
     <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
     <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
    <!-- MapQuest --> 
    <script src="http://www.mapquestapi.com/sdk/leaflet/v1.s/mq-map.js?key=Fmjtd%7Cluurn90rn1%2C7g%3Do5-9wtn0z"></script>
  </head>

  <body>
    <nav class="top-bar" role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "OpenRallyMap", root_path %></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
		<ul class="right">
			<li class="has-dropdown">
				<a href="#">
					<i class="fi-list"></i>
				</a>
				<ul class="dropdown">
					<li><a href="#">First link in dropdown</a></li>
					<% if contributor_signed_in?%>
						<li>
							<%= link_to raw('<i class="fi-home"></i> dashboard'), dashboard_path %>
						</li>
						<li>
							<%= link_to raw('<i class="fi-torso"></i> sign out'), destroy_contributor_session_path, :method => :delete %>
						</li>
					<% else%>
						<li>
							<%= link_to raw('<i class="fi-torso"></i> sign in'), new_contributor_session_path %>
						</li>
					<% end %>
				</ul>
			</li>
		</ul>
      </section>
    </nav>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/moments/_form.html.erb
<%= simple_form_for @moment do |f| %>
  <% if @moment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moment.errors.count, "error") %> prohibited this moment from being saved:</h2>

      <ul>
      <% @moment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="row">
		<div class="small-12 medium-4 columns">
			<div class="row">
				<div class="small-12 medium-6 columns">
					<%= f.input :active %>
				</div>
				<div class="small-12 medium-6 columns">
					<%= f.association :race_day, :collection => RaceDay.all.map{ |rd| ["#{rd.race.name} : #{rd.name} #{rd.race_date}", rd.id]}%>
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns">
					<%= f.input :name %>
					<%= f.input :description %>
					<%= f.input :source %>
					<%= f.input :embedable_code %>
					<div class="small-12 columns tag-list" data-module="tag-list">
						<label for="tag_input">Tags:</label>
						<input type="text" id="comma_seperated_tag_string" name="comma_seperated_tag_string" placeholder="Add tags. Use commas to separate." />
						<div class="row">
							<div class="small-12 columns">
								<div id="tag-list-controls" class="hidden" style="display: none;">
									<%= f.association :tags, as: :check_boxes, :label => false, collection: @moment.tags.order(:name => :asc)%>
								</div>
								<div id="tag-list-display">
									<% @moment.tags.order(:name => :asc).each do |tag| %>
										<span class="label tag radius secondary">
											<%= tag.name %> 
											<a href="#" class="close" data-tag-id="<%= tag.id %>"><i class="fi-x"></i></a>
										</span>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="small-12 medium-8 columns">
			<div class="row">
				<div class="small-12 columns">
					<div id="map" class="contributor-map"></div>
				</div>
			</div>
			<div class="row">
				<div class="small-6 columns">
					<%= f.input :lat %>
				</div>
				<div class="small-6 columns">
					<%= f.input :long %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="small-12 medium-6 columns">
			  <div class="actions">
			    <%= f.button :submit, :class => 'tiny' %>
			  </div>
		</div>
	</div>
<% end %>

app/views/moments/edit.html.erb
<div class="row">
	<div class="small-12 columns">
		<h1>Editing moment</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @moment %> |
		<%= link_to 'Back', moments_path %>
	</div>
</div>

app/views/moments/index.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>Listing moments</h1>

		<table>
		  <thead>
		    <tr>
  		      <th colspan="2"></th>
			  <th>Name</th>
		      <th>Lat</th>
		      <th>Long</th>
		      <th>Active</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @moments.each do |moment| %>
		      <tr>
		        <td><%= link_to raw('<i class="fi-pencil"></i>'), edit_moment_path(moment) %></td>
		        <td><%= link_to raw('<i class="fi-trash"></i>'), moment, method: :delete %></td>
				<td><%= moment.name %></td>
		        <td><%= moment.lat %></td>
		        <td><%= moment.long %></td>
		        <td><%= moment.active ? raw('<i class="fi-check"></i>') : raw('<i class="fi-x"></i>') %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

		<br>

		<%= link_to 'New Moment', new_moment_path %>
	</div>
</div>

app/views/moments/new.html.erb
<div class="row">
	<div class="small-12 columns">
		<h1>New moment</h1>

		<%= render 'form' %>

		<%= link_to 'Back', moments_path %>
	</div>
</div>

app/views/pages/dashboard.html.erb
<div class="row">
	<div class="small-12 columns">
		<h1>Dashboard</h1>
	</div>
</div>		
<div class="row">
	<div class="small-12 medium-2 columns">
		<h3>
			<%= link_to "Races", races_path %>
		</h3>
		<h3>
			<%= link_to "Race Days", race_days_path %>
		</h3>
		<h3>	
			<%= link_to "Moments", moments_path %>
		</h3>
		<h3>	
			<%= link_to "Tags", tags_path %>
		</h3>
	</div>
	<div class="small-12 medium-10 columns">
	</div>
</div>

app/views/pages/main.html.erb
<div class="row full-width">
  <div id="map-container" class="small-8 columns">
    <div id="map" class="main-map"></div>
  </div>
  <div id="content-pane" class="small-4 columns">
	  <dl class="accordion" data-accordion>
	    <dd class="accordion-navigation">
	      <a href="#map-tags">filter map tags</a>
	      <div id="map-tags" class="content">
		  	  <%
		  		current_race_day = RaceDay.where("race_date = '#{Date.today}'").first
		  		current_race_day = current_race_day.nil? ? Date.today : current_race_day
		  	  %>
		  	  <button data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">
		  		  <i class="fi-calendar"></i> <%= current_race_day %>
		  	  </button>
		  	  <ul id="drop1" class="f-dropdown  medium" data-dropdown-content aria-hidden="true" tabindex="-1">
		  			<% RaceDay.all.each do |race_date| %>
		  				<li>
		  					<a href="#"><%= "#{race_date.name} : #{race_date.race_date}"%></a>
		  				</li>
		  			<% end %>
		  	  </ul>
			<% @tags.each do |tag|%>
				<div class="row">
					<div class="small-1 columns">
						<input type="checkbox" name="<%= tag.name %>" value="<%= tag.name %>" class="tag-filter" checked>
					</div>
					<div class="small-11 columns">
						<%= tag.name %>
					</div>
				</div>
			<% end %>
	      </div>
	    </dd>
	    <dd class="accordion-navigation">
	      <a href="#content-accordian">content</a>
	      <div id="content-accordian" class="content active">
			  <div id="marker-embeddable-content">
		      </div>
	      </div>
	    </dd>
	  </dl>
  </div>
</div>

app/views/race_days/_form.html.erb
<%= form_for(@race_day) do |f| %>
  <% if @race_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race_day.errors.count, "error") %> prohibited this race_day from being saved:</h2>

      <ul>
      <% @race_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :race_date %><br>
    <%= f.date_select :race_date %>
  </div>
  <div class="field">
    <%= f.label :race_id %><br>
    <%= f.number_field :race_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/race_days/edit.html.erb
<h1>Editing race_day</h1>

<%= render 'form' %>

<%= link_to 'Show', @race_day %> |
<%= link_to 'Back', race_days_path %>

app/views/race_days/index.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>Listing Race Days</h1>
		<%= link_to 'New Race Day', new_race_day_path, :class => "button small" %>
		<table>
		  <thead>
		    <tr>
		      <th colspan="2"></th>
			  <th>Name</th>
		      <th>Race date</th>
		      <th>Race</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @race_days.each do |race_day| %>
		      <tr>
		        <td><%= link_to raw('<i class="fi-pencil"'), edit_race_day_path(race_day) %></td>
		        <td><%= link_to raw('<i class="fi-trash"'), race_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<td><%= race_day.name %></td>
		        <td><%= race_day.race_date %></td>
		        <td><%= race_day.race_id %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>

app/views/race_days/new.html.erb
<h1>New race_day</h1>

<%= render 'form' %>

<%= link_to 'Back', race_days_path %>

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_day_id %><br>
    <%= f.number_field :start_day_id %>
  </div>
  <div class="field">
    <%= f.label :end_day_id %><br>
    <%= f.number_field :end_day_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>Editing race</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @race %> |
		<%= link_to 'Back', races_path %>
	</div>
</div>

app/views/races/index.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>Listing Races</h1>
		<%= link_to 'New Race', new_race_path, :class => 'button tiny' %>
		<table>
		  <thead>
		    <tr>
		      <th colspan="2"></th>
		      <th>Name</th>
		      <th>Start day</th>
		      <th>End day</th>

		    </tr>
		  </thead>

		  <tbody>
		    <% @races.each do |race| %>
		      <tr>
		        <td><%= link_to raw('<i class="fi-pencil"'), edit_race_path(race) %></td>
		        <td><%= link_to raw('<i class="fi-trash"'), race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<td><%= race.name %></td>
		        <td><%= race.start_day.race_date %></td>
		        <td><%= race.end_day.race_date %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>

app/views/races/new.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>New race</h1>
		<%= render 'form' %>
		<%= link_to 'Back', races_path %>
	</div>
</div>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_default %><br>
    <%= f.check_box :is_default %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>Editing tag</h1>
		<%= render 'form' %>
		<%= link_to 'Show', @tag %> |
		<%= link_to 'Back', tags_path %>
	</div>
</div>

app/views/tags/index.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>Listing tags</h1>
		<%= link_to 'New Tag', new_tag_path, :class => "button tiny" %>
		<table>
		  <thead>
		    <tr>
		      <th colspan="2"></th>
		      <th>Name</th>
		      <th>Active</th>
			  <th>Default</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @tags.each do |tag| %>
		      <tr>
		        <td><%= link_to raw('<i class="fi-pencil"></i>'), edit_tag_path(tag) %></td>
		        <td><%= link_to raw('<i class="fi-trash"></i>'), tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		        <td><%= tag.name %></td>
		        <td><%= tag.active ? raw('<i class="fi-check"></i>') : raw('<i class="fi-x"></i>') %></td>
				<td><%= tag.is_default ? raw('<i class="fi-check"></i>') : raw('<i class="fi-x"></i>') %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>

app/views/tags/new.html.erb
<div class="row">
	<div class="small-12 medium-8 columns">
		<h1>New tag</h1>
		<%= render 'form' %>
		<%= link_to 'Back', tags_path %>
	</div>
</div>